language: python

python:
  - "3.5"

services:
  - "mysql"

env:
  - BLOG_SECRET_KEY="te#!24a*(7#vdhvo%mev=ehj61puq(^z%^1caeiyf$yj2+9+p-"

# command to install dependencies
install: "pip install -r requirements/test.txt"

before_script:
  - "mysql -e  'CREATE DATABASE djblog;'"
# command to run tests
script: "cd selfblog && python manage.py test --settings=selfblog.settings.test"
