# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 08:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('slug', models.SlugField(max_length=100, verbose_name='Slug')),
                ('content', models.TextField(verbose_name='Content')),
                ('content_html', models.TextField(editable=False, verbose_name='Html Content')),
                ('status', models.IntegerField(choices=[(0, 'Publish'), (1, 'Draft'), (2, 'Hidden')], default=1, verbose_name='Status')),
                ('published_time', models.DateTimeField(auto_now_add=True, verbose_name='Published Date')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
            ],
            options={
                'ordering': ['-published_time'],
                'verbose_name': 'Articles',
                'verbose_name_plural': 'Articles',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(max_length=40, verbose_name='Slug')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Categories',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('slug', models.SlugField(max_length=100, verbose_name='Slug')),
                ('content', models.TextField(verbose_name='Content')),
                ('content_html', models.TextField(editable=False, verbose_name='HTML Content')),
                ('rank', models.IntegerField(default=1, help_text='Display order', verbose_name='Rank')),
                ('status', models.IntegerField(choices=[(0, 'Publish'), (1, 'Draft'), (2, 'Hidden')], default=1, verbose_name='Status')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
            ],
            options={
                'ordering': ['-rank', '-created_time'],
                'verbose_name': 'Pages',
                'verbose_name_plural': 'Pages',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(max_length=40, verbose_name='Slug')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Tags',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Split with comma', related_name='articles', to='blog.Tag', verbose_name='Tags'),
        ),
    ]
